API/urls.py
from django.urls import path, include
from .viewSerializer import ProductoViewset
from rest_framework import routers

router = routers.DefaultRouter()

router.register('producto',ProductoViewset)

#Urls de la API
urlpatterns = [
    path('', include(router.urls)),
]

GameStore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('home.urls')),
    path('juegos/',include('gestionProducto.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('carro/', include('carro.urls')),
    path('api/', include('API.urls')),
    path('user_profile/', include('user_profile.urls')),

]

if settings.DEBUG:

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carro/urls.py
from django.urls import path
from . import views

app_name = "carro"

urlpatterns = [

    path('', views.vista_carro, name='carro'),
    path('agregar/<int:producto_id>',views.agregar_producto, name='agregar'),
    path('eliminar/<int:producto_id>',views.eliminiar_producto, name='eliminar'),
    path('restar/<int:producto_id>',views.restar_producto, name='restar'),
    path('limpiar/',views.limpiar_carro, name='limpiar'),
]

gestionProducto/urls.py
from django.urls import path
from . import views

app_name='gestion'

urlpatterns = [
    path('',views.juegos, name='juegos'),
    path('detalle_juego/<int:producto_id>',views.detalle_juego, name='detalle_juego'),
    
]

home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('',views.home, name='home'),
    path('registro/', views.registro, name='registro'),
]

user_profile/urls.py
from django.urls import path
from . import views

app_name = "user_profile"

urlpatterns = [
    path('',views.user_profile, name='user_profile'),
]

gestionProducto/models.py
from django.db import models

# Create your models here.

class Plataforma(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre


class Producto(models.Model):
    nombre = models.CharField(max_length=100)
    imagen = models.ImageField(upload_to="productos",null=True)
    trailer = models.URLField(max_length=200, null=True)
    precio = models.IntegerField()
    detalle = models.TextField()
    plataforma = models.ForeignKey(Plataforma, on_delete=models.PROTECT)

    def __str__(self):
        return self.nombre
    
class ImagenProducto(models.Model):
    imagen = models.ImageField(upload_to='productos')
    producto = models.ForeignKey(Producto, on_delete=models.CASCADE, default=1, related_name='imagenes')

user_profile/models.py
from django.db import models

# Create your models here.

home/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = User
        fields = ['first_name','last_name','email','username','password1','password2']


    

carro/views.py
from django.shortcuts import render,redirect
from .carro import Carro
from gestionProducto.models import Producto
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

# Create your views here.
def vista_carro(request):

    return render(request,'carro.html')

@login_required
def agregar_producto(request,producto_id):

    carro = Carro(request)
    producto = Producto.objects.get(id=producto_id)
            
    carro.agregar(producto = producto)

    return redirect("carro:carro")

def eliminiar_producto(request,producto_id):

    carro = Carro(request)

    producto = Producto.objects.get(id=producto_id)

    carro.eliminar(producto = producto)

    return redirect("carro:carro")

def restar_producto(request,producto_id):

    carro = Carro(request)

    producto = Producto.objects.get(id=producto_id)

    carro.restar_producto(producto = producto)

    return redirect("carro:carro")

def limpiar_carro(request):

    carro = Carro(request)
    carro.limpiar_carro()

    return redirect("carro:carro")

gestionProducto/views.py
from django.shortcuts import render
from . models import Producto
from django.db.models import Q

# Create your views here.

def juegos (request):

    juegos = Producto.objects.all()

    queryset = request.GET.get('buscador')

    if queryset:
        
        juegos = Producto.objects.filter(

            Q(nombre__icontains = queryset) 

        ).distinct()

        

    data={
        'juegos':juegos
    } 
    return render(request,'juegos.html', data)

def detalle_juego(request,producto_id):

    juego = Producto.objects.filter(id=producto_id)

    data ={
        'juego':juego
    }
    
    return render(request,'detalle_juego.html', data)

home/views.py
from django.shortcuts import render, redirect
from . forms import CustomUserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib import messages
from gestionProducto.models import Producto
from django.db.models import Q
# Create your views here.


def home (request):

    #Seccion de buscador

    queryset = request.GET.get('buscador')
    print(queryset)

    if queryset:
        
        respuesta = Producto.objects.filter(
            Q(nombre__icontains = queryset)
        ).distinct()

    return render(request,'home.html')


def registro(request):

    form = CustomUserCreationForm

    data = {
        'form': form
    }

    if request.method=='POST':
        formulario = CustomUserCreationForm(data=request.POST)

        if formulario.is_valid():
            formulario.save()
            user = authenticate(username= formulario.cleaned_data["username"], password = formulario.cleaned_data["password1"])
            login(request,user)
            #Redirigir al home
            messages.success(request,'Registrado correctamente')
            return redirect(to='home:home')
        data["form"] = formulario


    return render(request,'registration/registro.html', data)

user_profile/views.py
from django.shortcuts import render

# Create your views here.

def user_profile(request):

    return render(request,'user_profile.html')

carro/templates/carro.html
{% extends 'base.html' %}

<!--todo| CONTENIDO PRINCIPAL DE LA PAGINA-->
{% block content %}

{% load static %}

{% load humanize %}

<div class="container">
    <div class="row">

        <h2 class="m-3">Mi Carrito</h2>

        <div class="col-lg-8">

            {% if request.session.carro.items %}
            {% for key, value in request.session.carro.items %}

            <div class="row shadow rounded-5 p-3 m-2" style="background-color: #030616;">
                <!-- style="background-color: black;" -->

                <div class="col-2">
                    <img src="{{value.imagen}}" alt="" height="" width="120px">
                </div>

                <div class="col-10 row">

                    <div class="col-11">
                        <p class="fs-3">{{value.nombre}}</p>

                    </div>

                    <div class="col-1">
                        <button class="fs-4 link-light link-offset-2 link-underline-opacity-25 link-underline-opacity-100-hover"
                            onclick="eliminarCarro({{value.producto_id}})"><i
                                class="fa-regular fa-trash-can"></i></button>

                    </div>

                    <div class="col-12">
                        <p>Plataforma {{value.plataforma}}</p>

                    </div>

                    <div class="col-6">
                        <p>{{value.precio}} CLP</p>
                    </div>

                    <div class="col-6">

                        <a href="{% url 'carro:restar' value.producto_id %}">-</a>
                        <span>{{value.cantidad}}</span>

                        <a href="{% url 'carro:agregar' value.producto_id %}">+</a>

                    </div>

                </div>

            </div>

            {% endfor %}
            {% else %}

            <div class="row shadow rounded-5">

                <div class="col">

                    <h2>Tu carrito esta vacio</h2>
                </div>


            </div>

            {% endif %}



        </div>

        {% if request.session.carro.items %}


        <div class="col m-2 p-3 rounded-5 shadow" style="background-color: #030616;">

            <div class="summary-box p-2">

                <div class="d-flex justify-content-between">
                    <span>{{cantidad_carro}} productos</span>
                    <span>{{importe_total_carro}}</span>
                </div>

                <div class="d-flex justify-content-between">
                    <span>Tarifa de servicio</span>
                    <span>--</span>
                </div>

                <hr>

                <div class="d-flex justify-content-between total-price fs-2">
                    <span>Total:</span>
                    <span>{{importe_total_carro | intcomma}} CLP</span>
                </div>

                <hr>

                <div class="text-center mb-3">
                    <span>¿Tienes un código de descuento?</span>
                </div>

                <div class="review-section">

                    <form class="row g-3">
                        <div class="col-9">
                            <label for="descuento" class="visually-hidden">xxxx-xxxx-xxxx</label>
                            <input type="text" class="form-control" id="descuento" placeholder="xxxx-xxxx-xxxx">
                        </div>
                        <div class="col-3">
                            <button type="submit" class="btn btn-primary mb-3">Aplicar</button>
                        </div>
                    </form>

                </div>

                <div class="text-center mt-5">
                    <button class="btn btn-outline-light">Continuar con la compra</button>
                </div>
            </div>
        </div>

        {% endif %}
    </div>

</div>


{% endblock content %}


{% block js %}

<script src="{% static 'js/carro.js' %}"></script>
    
{% endblock js %}
    

gestionProducto/templates/detalle_juego.html
{% extends 'base.html' %}

{% load static %}


{% block title %}
<title>Juego</title>
{% endblock title %}

{% load humanize %}


{% block content %}
{% for i in juego %}

<div class="container">

    <div class="row p-3">

        <!--todo | Imagen |-->
        <div class="col-lg-3">
            <img src="{{i.imagen.url}}" alt="" class="img-fluid">
        </div>

        <!--todo| Nombre e Informacion |-->
        <div class="col-lg-6 text-center ">

            <p class="fs-3 fw-bold text mt-2">{{i.nombre}}</p>

            <hr>

            <div class="row mt-5 text-start">

                <div class="col">
                    <p>Este producto es de {{i.plataforma}}</p>
                </div>

                <div class="col">
                    <span class="fw-bold">{{i.plataforma}}</span><br>
                    <span class="opacity-75" style="font-size: small;">Se activa en <a href="#">{{i.plataforma}}</a></span><br>
                    <span class="opacity-75" style="font-size: small;">Consulta la guia de <a href="#">Activacion</a></span>
                </div>

                <div class="col ">
                    <span class="fw-bold">Código Digital</span><br>
                    <span class="opacity-75" style="font-size: small;">Esta es una edición digital del producto (CD-KEY)</span>
                </div>

            </div>

            <hr>

        </div>


        <!--todo | Compra |-->
        <div class="col-lg-3 shadow">

            <div>

                <p class="fs-2 text">{{i.precio | intcomma}} CLP</p>

            </div>

            <div class="d-grid gap-2">
                <button class="btn btn-warning" type="button">Comprar ahora</button>
                <button class="btn btn-outline-primary"  onclick="agregarAlCarro({{ i.id }})">
                    <i class="fa-solid fa-cart-shopping"></i>
                    Añadir al carrito
                </button>
            </div>

        </div>

    </div>

    <!--todo| Sona de fotos-->
    <div class="row shadow mt-3">

        <div class="col-lg-2">
            {% if i.trailer %}
            <div class="ratio ratio-16x9">
                <iframe width="560" height="315" src="{{i.trailer}}
                title=" YouTube video player" frameborder="0"
                    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
                    allowfullscreen>
                </iframe>
            </div>
            {% else %}
            <p>No tiene trailer :(</p>
            {% endif %}

        </div>

        {% for m in i.imagenes.all %}
        <div class="col-lg-2">
            <img src="{{m.imagen.url}}" class="img-fluid" alt="Imagen de producto">
        </div>
        {% endfor %}

    </div>

    <!--todo| Sona de Descripcion-->
    <div class="row shadow mt-3">
        <h3>Detalles del producto</h3>
        <p>{{i.detalle}}</p>
    </div>

</div>


{% endfor %}
{% endblock content %}


{% block js %}

<script src="{% static 'js/gestion.js' %}"></script>

{% endblock js %}


    

gestionProducto/templates/juegos.html
{% extends 'base.html' %}


{% block title %} <title>Juegos</title> {% endblock title %}



{% block content %}

{% load humanize %}
{% load static %}

<head>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>


<div class="container p-5">
    <div class="row">

        <h2>Tienda</h2>

        <div class=" row col-lg-2" style="border: solid red 1px;">

            <div class="col-12">
                <span>Plataformas</span>

            </div>

            <div class="col-12">
                <span>Categoria</span>
    
            </div>

            <div class="col-12">
                <span>Genero</span>

            </div>
            
        </div>

        <div class="col-lg-10">

            <p>Esta es la pagina de los juegos</p>

            <!--todo| CARD ORIGINAL-->

            <div class="row row-cols-1 row-cols-md-3 g-4 p-5">
                {% for i in juegos %}
                <a href="{% url 'gestion:detalle_juego' i.id %}" style="text-decoration: none;">
                    <div class="col">
                        <div class="card h-100 card-custom-size" style="background-color: #030616; color: white;">
                            <img src="{{i.imagen.url}}" class="img-card-top p-3" alt="...">
                            
                            <div class="card-footer">
                                <p class="card-text">{{i.plataforma}}</p>
                                <p>{{i.nombre}}</p>
                                <div class="d-flex justify-content-between align-items-center mt-3">
                                    <span class="fw-bold fs-5">{{i.precio | intcomma}} CLP</span>
                                    <!-- <span>+<i class="fa-solid fa-cart-shopping"></i></span> -->
                                </div>
                            </div>
                        </div>
                    </div>
                </a>
                {% endfor %}
            </div>

            
        </div>
    </div>
</div>

    {% endblock content %}

home/templates/busqueda/busqueda.html
{% extends 'base.html' %}


{% block content %}

<h1>LO BUSCADO</h1>
<p>{{respuesta}}</p>
    
{% endblock content %}
    

home/templates/home.html
{% extends 'base.html' %}


{% block content %}

{% load static %}

<div class="container">


    <!--todo| CARRUSEL |-->
    <div id="carouselExampleAutoplaying" class="carousel slide" data-bs-ride="carousel">
        <div class="carousel-inner">
            <div class="carousel-item active">
                <a href="#"><img src="{% static 'img/carr1.png' %}" class="d-block w-100" alt="..."></a>
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/carr2.png' %}" class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="{% static 'img/carr3.jpg' %}" class="d-block w-100" alt="...">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleAutoplaying"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleAutoplaying"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>

    <!--todo| | -->
    <div class="row mt-5">

        <div class="col-12">

            <p class="fs-2">Ofertas especiales!</p>

        </div>

        <div class="col-12">

            <p class="fs-2">Juegos populares</p>

        </div>

    </div>

</div>


{% endblock content %}